apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: toolbox-container
  newName: quay.io/noseka1/toolbox-container
  newTag: basic

configMapGenerator:
- name: toolbox-container-init
  files:
  - init.sh

resources:
- toolbox-container-deploy.yaml
- toolbox-container-sa.yaml
#- toolbox-container-home-pvc.yaml
#- toolbox-container-block-pvc.yaml
#- toolbox-container-scc-role.yaml
#- toolbox-container-scc-rolebinding.yaml
#- toolbox-container-cluster-admin-clusterrolebinding.yaml
#- toolbox-container-svc.yaml
#- toolbox-container-route.yaml

patches:
#- path: toolbox-container-deploy-hostNetwork.yaml
#- path: toolbox-container-deploy-hostPID.yaml
#- path: toolbox-container-deploy-hostIPC.yaml
#- path: toolbox-container-deploy-privileged.yaml
#- path: toolbox-container-deploy-capabilities.yaml
#- path: toolbox-container-deploy-home-pvc.yaml
#- path: toolbox-container-deploy-block-pvc.yaml
#- path: toolbox-container-deploy-hostPath-host.yaml
#- path: toolbox-container-deploy-hostPath-dev.yaml
#- path: toolbox-container-deploy-hostPath-proc.yaml
#- path: toolbox-container-deploy-hostPath-sys.yaml
#- path: toolbox-container-deploy-hostPath-root.yaml
#- path: toolbox-container-deploy-hostPath-run.yaml
#- path: toolbox-container-deploy-hostPath-run-dbus.yaml
#- path: toolbox-container-deploy-hostPath-lib-modules.yaml
#- path: toolbox-container-deploy-nodeName.yaml
#- path: toolbox-container-deploy-tolerations.yaml
#- path: toolbox-container-deploy-resources.yaml
#- path: toolbox-container-deploy-sleep.yaml
