apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - REPLACE_ME_WITH_THE_TARGET_CLUSTER_NODE_NAME
