apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toolbox-container-rbd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
