apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        livenessProbe:
          httpGet:
            # The following command can provide the probe endpoint:
            # gunicorn-3 --bind 0.0.0.0:8080 --access-logfile - httpbin:app
            path: /status/200
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
