apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toolbox-container-block
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  #storageClassName: iscsi-target
  volumeMode: Block
