apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: fs
          mountPath: /home/toolbox/fs
      volumes:
      - name: fs
        persistentVolumeClaim:
          claimName: toolbox-container-fs
