apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: run-dbus
          mountPath: /run/dbus
      volumes:
      - name: run-dbus
        hostPath:
          path: /run/dbus
