apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toolbox-container-fs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
